import type { Metadata } from "next"

import { LegalPage } from "@/components/legal/legal-page"

// Nonce-based CSP requires dynamic rendering — see src/app/(auth)/layout.tsx.
export const dynamic = "force-dynamic"

export const metadata: Metadata = {
  title: "Terms of service",
  description: "The terms that apply to this starter kit.",
}

export default function TermsPage() {
  return (
    <LegalPage title="Terms of service" updated="23 July 2026">
      <p>
        This project is an open-source starter kit distributed as example code. It is provided as
        is, without warranty of any kind, express or implied. Nothing here constitutes a commercial
        service agreement.
      </p>

      <h2>Placeholder document</h2>
      <p>
        <strong>This page is a template, not legal advice.</strong> It exists so the sign-up flow
        links somewhere real rather than to a dead route. Before running anything derived from this
        kit in production, replace this text with terms drafted for your jurisdiction and business.
      </p>

      <h2>Demo data</h2>
      <p>
        Every figure in this dashboard is generated by a deterministic seeded function. It does not
        describe any real person, company, or account. The demo credentials shown on the sign-in
        page are published intentionally and protect nothing.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You may use, modify, and redistribute this code under the terms of its licence. You may not
        present the generated demo figures as genuine analytics for a real business.
      </p>

      <h2>Liability</h2>
      <p>
        The authors accept no liability for any loss arising from use of this code. Anything you
        deploy from it — and any real user data it then handles — is your responsibility.
      </p>
    </LegalPage>
  )
}
